CREATE TABLE IF NOT EXISTS memos (
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    text TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
